### ISSUE TITLE
configure fails to find oneDNN

### ISSUE THREAD

**Issue by yurivict** [flashlight/flashlight#1088]
### Bug Description
```
CMake Warning at flashlight/fl/tensor/backend/onednn/CMakeLists.txt:6 (find_package):
  Could not find a configuration file for package "DNNL" that is compatible
  with requested version "2.5.2".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/dnnl/dnnl-config.cmake, version: 3.0.1

Call Stack (most recent call first):
  flashlight/fl/tensor/CMakeLists.txt:45 (include)
  flashlight/fl/CMakeLists.txt:32 (include)
  CMakeLists.txt:181 (include)


CMake Error at flashlight/fl/tensor/backend/onednn/CMakeLists.txt:8 (message):
  oneDNN required to build oneDNN backend: oneDNN was not found
Call Stack (most recent call first):
  flashlight/fl/tensor/CMakeLists.txt:45 (include)
  flashlight/fl/CMakeLists.txt:32 (include)
  CMakeLists.txt:181 (include)
```

#### Reproduction Steps
Regular configure.

### Platform and Hardware
FreeBSD 13.1

#### Additional Context
Version: 0.4.0
onednn-3.0.1 (latest version)
clang-14

**Comment by jacobkahn** [comment]
@yurivict oneDNN breaks their API with new releases -- I'm working on supporting 3.0+. Thanks for reporting.

**Comment by vpirogov** [comment]
oneDNN follows [semantic versioning](https://semver.org/). API breaks only between major versions. Minor versions are API compatible.

**Comment by tlyong3** [comment]
@jacobkahn any update on your fix for oneDNN 3.x support? I forced it to build with v3.0 or 3.1 but getting many errors such as this:
/root/flashlight/flashlight/fl/tensor/backend/onednn/OneDnnBackend.cpp:180:18: error: ‘const struct dnnl::memory::desc’ has no member named ‘data_type’; did you mean ‘get_data_type’?
  180 |       lhsMemDesc.data_type(), rhsMemDesc.data_type()));
      |                  ^~~~~~~~~
      |                  get_data_type
