### ISSUE TITLE
OpenClUtils.h not found

### ISSUE THREAD

**Issue by felixt56** [flashlight/flashlight#880]
### Bug Description
cmake .. -DFL_ARRAYFIRE_USE_OPENCL=ON -DFL_USE_OPENCL=ON
make
flashlight/fl/autograd/tensor/backend/onednn/DnnlUtils.cpp:22:12: fatal error: flashlight/fl/common/OpenClUtils.h: No such file or directory

#### Reproduction Steps
cmake .. -DFL_ARRAYFIRE_USE_OPENCL=ON -DFL_USE_OPENCL=ON
make
flashlight/fl/autograd/tensor/backend/onednn/DnnlUtils.cpp:22:12: fatal error: flashlight/fl/common/OpenClUtils.h: No such file or directory

### Platform and Hardware
[Ubuntu 20.04 focal (x86-64)]

#### Additional Context
[Add any additional information here]

**Comment by jacobkahn** [comment]
@felixt56 — the OpenCL backend isn't supported at the moment. We're working on adding it back in the next several weeks. It should build in theory in v0.3.2 — can you try checking that version out and building?

**Comment by felixt56** [comment]
Thanks
Maybe I'll try it next month.

**Comment by felixt56** [comment]
Sorry, I hadn't time to check for now
